apiVersion: v1
kind: ReplicationController
metadata:
  name: rc1
spec:
  replicas: 2
  selector:
   dc: "India"
  template:
    metadata:
      name: "pod1"
      labels:
        dc: "India"
    spec:
      containers:
      - name: "mycr1"
        image: "vimal13/apache-webserver-php"